#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 250
#define IGNORE_MOD_TAP_INTERRUPT

#define ONESHOT_TAP_TOGGLE 2
#undef ONESHOT_TIMEOUT 
#define ONESHOT_TIMEOUT 10000

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 25
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#define COMBO_COUNT 2
#define COMBO_TERM 20

#define TAPPING_TOGGLE 1

